service: sublimate-profile

provider:
  name: aws
  runtime: nodejs12.x

functions:
  update:
    handler: handler.updateProfile
    events:
      - httpApi:
        method: POST
        path: /profile

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline